import { keys } from "rambda"

export type SimpleMonster = {
  level: number,
  armor_class: number,
  hit_points: number,
  attack_bonus: number,
  damage_per_action: number,
  spell_dc: [number, number],
  perception: number,
  proficiency_bonus: number,
  saving_throws: [number, number, number],
  ability_modifiers: [number, number, number, number, number, number],
  experience: number,
}

export const levels: SimpleMonster[] = [
  {
    level: -5,
    armor_class: 11,
    hit_points: 1,
    attack_bonus: -1,
    damage_per_action: 1,
    spell_dc: [8, 5],
    perception: 0,
    proficiency_bonus: 0,
    saving_throws: [1, 0, -1],
    ability_modifiers: [1, 0, 0, 0, 0, -1],
    experience: 0,
  },
  {
    level: -4,
    armor_class: 12,
    hit_points: 1,
    attack_bonus: 0,
    damage_per_action: 1,
    spell_dc: [9, 6],
    perception: 1,
    proficiency_bonus: 0,
    saving_throws: [2, 1, -1],
    ability_modifiers: [2, 1, 1, 0, 0, -1],
    experience: 0,
  },
  {
    level: -3,
    armor_class: 13,
    hit_points: 4,
    attack_bonus: 1,
    damage_per_action: 1,
    spell_dc: [10, 7],
    perception: 1,
    proficiency_bonus: 1,
    saving_throws: [3, 1, 0],
    ability_modifiers: [2, 1, 1, 0, 0, -1],
    experience: 2,
  },
  {
    level: -2,
    armor_class: 13,
    hit_points: 8,
    attack_bonus: 1,
    damage_per_action: 1,
    spell_dc: [10, 7],
    perception: 1,
    proficiency_bonus: 1,
    saving_throws: [3, 1, 0],
    ability_modifiers: [2, 1, 1, 0, 0, -1],
    experience: 6,
  },
  {
    level: -1,
    armor_class: 13,
    hit_points: 12,
    attack_bonus: 1,
    damage_per_action: 1,
    spell_dc: [10, 7],
    perception: 1,
    proficiency_bonus: 1,
    saving_throws: [3, 1, 0],
    ability_modifiers: [2, 1, 1, 0, 0, -1],
    experience: 12,
  },
  {
    level: 0,
    armor_class: 14,
    hit_points: 16,
    attack_bonus: 2,
    damage_per_action: 1,
    spell_dc: [10, 7],
    perception: 1,
    proficiency_bonus: 1,
    saving_throws: [4, 2, 0],
    ability_modifiers: [3, 2, 1, 1, 0, -1],
    experience: 25,
  },
  {
    level: 1,
    armor_class: 14,
    hit_points: 26,
    attack_bonus: 3,
    damage_per_action: 2,
    spell_dc: [11, 8],
    perception: 1,
    proficiency_bonus: 2,
    saving_throws: [5, 3, 0],
    ability_modifiers: [3, 2, 1, 1, 0, -1],
    experience: 50,
  },
  {
    level: 2,
    armor_class: 14,
    hit_points: 30,
    attack_bonus: 3,
    damage_per_action: 4,
    spell_dc: [11, 8],
    perception: 1,
    proficiency_bonus: 2,
    saving_throws: [5, 3, 0],
    ability_modifiers: [3, 2, 1, 1, 0, -1],
    experience: 112,
  },
  {
    level: 3,
    armor_class: 14,
    hit_points: 33,
    attack_bonus: 3,
    damage_per_action: 5,
    spell_dc: [11, 8],
    perception: 1,
    proficiency_bonus: 2,
    saving_throws: [5, 3, 0],
    ability_modifiers: [3, 2, 1, 1, 0, -1],
    experience: 175,
  },
  {
    level: 4,
    armor_class: 15,
    hit_points: 36,
    attack_bonus: 4,
    damage_per_action: 8,
    spell_dc: [12, 9],
    perception: 2,
    proficiency_bonus: 2,
    saving_throws: [6, 3, 1],
    ability_modifiers: [4, 3, 2, 1, 1, 0],
    experience: 275,
  },
  {
    level: 5,
    armor_class: 16,
    hit_points: 60,
    attack_bonus: 5,
    damage_per_action: 10,
    spell_dc: [13, 10],
    perception: 2,
    proficiency_bonus: 3,
    saving_throws: [7, 4, 1],
    ability_modifiers: [4, 3, 2, 1, 1, 0],
    experience: 450,
  },
  {
    level: 6,
    armor_class: 16,
    hit_points: 64,
    attack_bonus: 5,
    damage_per_action: 11,
    spell_dc: [13, 10],
    perception: 2,
    proficiency_bonus: 3,
    saving_throws: [7, 4, 1],
    ability_modifiers: [4, 3, 2, 1, 1, 0],
    experience: 575,
  },
  {
    level: 7,
    armor_class: 16,
    hit_points: 68,
    attack_bonus: 5,
    damage_per_action: 13,
    spell_dc: [13, 10],
    perception: 2,
    proficiency_bonus: 3,
    saving_throws: [7, 4, 1],
    ability_modifiers: [4, 3, 2, 1, 1, 0],
    experience: 725,
  },
  {
    level: 8,
    armor_class: 17,
    hit_points: 72,
    attack_bonus: 6,
    damage_per_action: 17,
    spell_dc: [14, 11],
    perception: 3,
    proficiency_bonus: 3,
    saving_throws: [8, 5, 1],
    ability_modifiers: [5, 3, 2, 2, 1, 0],
    experience: 975,
  },
  {
    level: 9,
    armor_class: 18,
    hit_points: 102,
    attack_bonus: 7,
    damage_per_action: 19,
    spell_dc: [15, 12],
    perception: 3,
    proficiency_bonus: 4,
    saving_throws: [9, 5, 2],
    ability_modifiers: [5, 3, 2, 2, 1, 0],
    experience: 1250,
  },
  {
    level: 10,
    armor_class: 18,
    hit_points: 107,
    attack_bonus: 7,
    damage_per_action: 21,
    spell_dc: [15, 12],
    perception: 3,
    proficiency_bonus: 4,
    saving_throws: [9, 5, 2],
    ability_modifiers: [5, 3, 2, 2, 1, 0],
    experience: 1475,
  },
  {
    level: 11,
    armor_class: 18,
    hit_points: 111,
    attack_bonus: 7,
    damage_per_action: 23,
    spell_dc: [15, 12],
    perception: 3,
    proficiency_bonus: 4,
    saving_throws: [9, 5, 2],
    ability_modifiers: [5, 3, 2, 2, 1, 0],
    experience: 1800,
  },
  {
    level: 12,
    armor_class: 18,
    hit_points: 115,
    attack_bonus: 8,
    damage_per_action: 28,
    spell_dc: [15, 12],
    perception: 3,
    proficiency_bonus: 4,
    saving_throws: [10, 6, 2],
    ability_modifiers: [6, 4, 3, 2, 1, 0],
    experience: 2100,
  },
  {
    level: 13,
    armor_class: 19,
    hit_points: 152,
    attack_bonus: 9,
    damage_per_action: 30,
    spell_dc: [16, 13],
    perception: 3,
    proficiency_bonus: 5,
    saving_throws: [11, 7, 2],
    ability_modifiers: [6, 4, 3, 2, 1, 0],
    experience: 2500,
  },
  {
    level: 14,
    armor_class: 19,
    hit_points: 157,
    attack_bonus: 9,
    damage_per_action: 32,
    spell_dc: [16, 13],
    perception: 3,
    proficiency_bonus: 5,
    saving_throws: [11, 7, 2],
    ability_modifiers: [6, 4, 3, 2, 1, 0],
    experience: 2875,
  },
  {
    level: 15,
    armor_class: 19,
    hit_points: 162,
    attack_bonus: 9,
    damage_per_action: 35,
    spell_dc: [16, 13],
    perception: 3,
    proficiency_bonus: 5,
    saving_throws: [11, 7, 2],
    ability_modifiers: [6, 4, 3, 2, 1, 0],
    experience: 3250,
  },
  {
    level: 16,
    armor_class: 20,
    hit_points: 167,
    attack_bonus: 10,
    damage_per_action: 41,
    spell_dc: [17, 14],
    perception: 4,
    proficiency_bonus: 5,
    saving_throws: [12, 7, 3],
    ability_modifiers: [7, 5, 3, 2, 2, 1],
    experience: 3750,
  },
  {
    level: 17,
    armor_class: 21,
    hit_points: 210,
    attack_bonus: 11,
    damage_per_action: 43,
    spell_dc: [18, 15],
    perception: 4,
    proficiency_bonus: 6,
    saving_throws: [13, 8, 3],
    ability_modifiers: [7, 5, 3, 2, 2, 1],
    experience: 4500,
  },
  {
    level: 18,
    armor_class: 21,
    hit_points: 216,
    attack_bonus: 11,
    damage_per_action: 46,
    spell_dc: [18, 15],
    perception: 4,
    proficiency_bonus: 6,
    saving_throws: [13, 8, 3],
    ability_modifiers: [7, 5, 3, 2, 2, 1],
    experience: 5000,
  },
  {
    level: 19,
    armor_class: 21,
    hit_points: 221,
    attack_bonus: 11,
    damage_per_action: 48,
    spell_dc: [18, 15],
    perception: 4,
    proficiency_bonus: 6,
    saving_throws: [13, 8, 3],
    ability_modifiers: [7, 5, 3, 2, 2, 1],
    experience: 5500,
  },
  {
    level: 20,
    armor_class: 22,
    hit_points: 226,
    attack_bonus: 12,
    damage_per_action: 51,
    spell_dc: [19, 16],
    perception: 5,
    proficiency_bonus: 6,
    saving_throws: [14, 9, 3],
    ability_modifiers: [8, 6, 4, 3, 2, 1],
    experience: 6250,
  },
  {
    level: 21,
    armor_class: 22,
    hit_points: 276,
    attack_bonus: 13,
    damage_per_action: 53,
    spell_dc: [20, 17],
    perception: 5,
    proficiency_bonus: 7,
    saving_throws: [15, 9, 4],
    ability_modifiers: [8, 6, 4, 3, 2, 1],
    experience: 8250,
  },
  {
    level: 22,
    armor_class: 22,
    hit_points: 282,
    attack_bonus: 13,
    damage_per_action: 56,
    spell_dc: [20, 17],
    perception: 5,
    proficiency_bonus: 7,
    saving_throws: [15, 9, 4],
    ability_modifiers: [8, 6, 4, 3, 2, 1],
    experience: 10250,
  },
  {
    level: 23,
    armor_class: 22,
    hit_points: 288,
    attack_bonus: 13,
    damage_per_action: 58,
    spell_dc: [20, 17],
    perception: 5,
    proficiency_bonus: 7,
    saving_throws: [15, 9, 4],
    ability_modifiers: [8, 6, 4, 3, 2, 1],
    experience: 12500,
  },
  {
    level: 24,
    armor_class: 23,
    hit_points: 294,
    attack_bonus: 14,
    damage_per_action: 61,
    spell_dc: [20, 17],
    perception: 5,
    proficiency_bonus: 7,
    saving_throws: [16, 10, 4],
    ability_modifiers: [9, 6, 4, 3, 2, 1],
    experience: 15500,
  },
  {
    level: 25,
    armor_class: 24,
    hit_points: 350,
    attack_bonus: 15,
    damage_per_action: 63,
    spell_dc: [21, 18],
    perception: 5,
    proficiency_bonus: 8,
    saving_throws: [17, 11, 4],
    ability_modifiers: [9, 6, 4, 3, 2, 1],
    experience: 18750,
  },
  {
    level: 26,
    armor_class: 24,
    hit_points: 357,
    attack_bonus: 15,
    damage_per_action: 66,
    spell_dc: [21, 18],
    perception: 5,
    proficiency_bonus: 8,
    saving_throws: [17, 11, 4],
    ability_modifiers: [9, 6, 4, 3, 2, 1],
    experience: 22500,
  },
  {
    level: 27,
    armor_class: 24,
    hit_points: 363,
    attack_bonus: 15,
    damage_per_action: 68,
    spell_dc: [21, 18],
    perception: 5,
    proficiency_bonus: 8,
    saving_throws: [17, 11, 4],
    ability_modifiers: [9, 6, 4, 3, 2, 1],
    experience: 26250,
  },
  {
    level: 28,
    armor_class: 25,
    hit_points: 369,
    attack_bonus: 16,
    damage_per_action: 71,
    spell_dc: [22, 19],
    perception: 6,
    proficiency_bonus: 8,
    saving_throws: [18, 11, 5],
    ability_modifiers: [10, 7, 5, 4, 3, 2],
    experience: 30000,
  },
  {
    level: 29,
    armor_class: 26,
    hit_points: 432,
    attack_bonus: 17,
    damage_per_action: 73,
    spell_dc: [23, 20],
    perception: 6,
    proficiency_bonus: 9,
    saving_throws: [19, 12, 5],
    ability_modifiers: [10, 7, 5, 4, 3, 2],
    experience: 33750,
  },
  {
    level: 30,
    armor_class: 26,
    hit_points: 439,
    attack_bonus: 17,
    damage_per_action: 76,
    spell_dc: [23, 20],
    perception: 6,
    proficiency_bonus: 9,
    saving_throws: [19, 12, 5],
    ability_modifiers: [10, 7, 5, 4, 3, 2],
    experience: 38750,
  },
  {
    level: 31,
    armor_class: 26,
    hit_points: 446,
    attack_bonus: 17,
    damage_per_action: 78,
    spell_dc: [23, 20],
    perception: 6,
    proficiency_bonus: 9,
    saving_throws: [19, 12, 5],
    ability_modifiers: [10, 7, 5, 4, 3, 2],
    experience: 44500,
  },
  {
    level: 32,
    armor_class: 26,
    hit_points: 453,
    attack_bonus: 18,
    damage_per_action: 81,
    spell_dc: [24, 21],
    perception: 7,
    proficiency_bonus: 9,
    saving_throws: [20, 13, 5],
    ability_modifiers: [11, 8, 5, 4, 3, 2],
    experience: 51000,
  },
  {
    level: 33,
    armor_class: 27,
    hit_points: 522,
    attack_bonus: 19,
    damage_per_action: 83,
    spell_dc: [25, 22],
    perception: 7,
    proficiency_bonus: 10,
    saving_throws: [21, 13, 6],
    ability_modifiers: [11, 8, 5, 4, 3, 2],
    experience: 58000,
  },
  {
    level: 34,
    armor_class: 27,
    hit_points: 530,
    attack_bonus: 19,
    damage_per_action: 86,
    spell_dc: [25, 22],
    perception: 7,
    proficiency_bonus: 10,
    saving_throws: [21, 13, 6],
    ability_modifiers: [11, 8, 5, 4, 3, 2],
    experience: 67750,
  },
  {
    level: 35,
    armor_class: 27,
    hit_points: 537,
    attack_bonus: 19,
    damage_per_action: 88,
    spell_dc: [25, 22],
    perception: 7,
    proficiency_bonus: 10,
    saving_throws: [21, 13, 6],
    ability_modifiers: [11, 8, 5, 4, 3, 2],
    experience: 77750,
  },
]

export type Stat = "str" | "dex" | "con" | "int" | "wis" | "cha"

export type Role = {
  armor_class: number,
  hit_points: number,
  attack_bonus: number,
  damage_per_action: number,
  saving_throws: number,
  attack_dcs: number,
  initiative: number,
  perception: number,
  speed: number,
  stat_priorities: [Stat, Stat, Stat, Stat, Stat, Stat,],
}

export type Roles = {
  controller: Role,
  defender: Role,
  lurker: Role,
  scout: Role,
  sniper: Role,
  striker: Role,
  supporter: Role,
}

export type RoleName = keyof Roles

export const roles: Roles = {
  controller: {
    armor_class: -2,
    hit_points: 1,
    attack_bonus: 0,
    damage_per_action: 1,
    saving_throws: -1,
    attack_dcs: 0,
    initiative: 2,
    perception: 0,
    speed: 0,
    stat_priorities: ["int", "dex", "con", "wis", "cha", "str"],
  },
  defender: {
    armor_class: 2,
    hit_points: 1,
    attack_bonus: 0,
    damage_per_action: 1,
    saving_throws: 1,
    attack_dcs: 0,
    initiative: 0,
    perception: 2,
    speed: -10,
    stat_priorities: ["con", "str", "dex", "wis", "cha", "int"],
  },
  lurker: {
    armor_class: -4,
    hit_points: 0.5,
    attack_bonus: 2,
    damage_per_action: 1.5,
    saving_throws: -2,
    attack_dcs: 2,
    initiative: 0,
    perception: 2,
    speed: 0,
    stat_priorities: ["dex", "wis", "con", "str", "int", "cha"],
  },
  scout: {
    armor_class: -2,
    hit_points: 1,
    attack_bonus: 0,
    damage_per_action: 0.75,
    saving_throws: -1,
    attack_dcs: 0,
    initiative: 2,
    perception: 2,
    speed: 10,
    stat_priorities: ["dex", "wis", "con", "str", "int", "cha"],
  },
  sniper: {
    armor_class: 0,
    hit_points: 0.75,
    attack_bonus: 0,
    damage_per_action: 1.25,
    saving_throws: 0,
    attack_dcs: 0,
    initiative: 0,
    perception: 0,
    speed: 0,
    stat_priorities: ["dex", "wis", "str", "int", "cha", "con"],
  },
  striker: {
    armor_class: -4,
    hit_points: 1.25,
    attack_bonus: 2,
    damage_per_action: 1.25,
    saving_throws: -2,
    attack_dcs: 2,
    initiative: 0,
    perception: 0,
    speed: 0,
    stat_priorities: ["str", "con", "dex", "wis", "cha", "int"],
  },
  supporter: {
    armor_class: -2,
    hit_points: 0.75,
    attack_bonus: 0,
    damage_per_action: 0.75,
    saving_throws: -1,
    attack_dcs: 0,
    initiative: 2,
    perception: 0,
    speed: 0,
    stat_priorities: ["wis", "con", "dex", "str", "int", "cha"],
  },
}


export type Modifier = {
  armor_class: number,
  attack_bonus: number,
  hit_points: number,
  damage_per_action: number,
  saving_throws: number,
  spell_dc: number,
  initiative: number,
  perception: number,
  stealth: number,
  experience: number,
  special: string[],
}

export type Modifiers = {
  normal: Modifier,
  minion: Modifier,
  elite: Modifier,
  solo: Modifier,
}

export type ModifierName = keyof Modifiers

export const modifiers: Modifiers = {
  normal: {
    armor_class: 0,
    attack_bonus: 0,
    hit_points: 1,
    damage_per_action: 1,
    saving_throws: 0,
    spell_dc: 0,
    initiative: 0,
    perception: 0,
    stealth: 0,
    experience: 1,
    special: [],
  },
  minion: {
    armor_class: -2,
    attack_bonus: -2,
    hit_points: 0.2,
    damage_per_action: 0.75,
    saving_throws: -2,
    spell_dc: -2,
    initiative: -2,
    perception: -2,
    stealth: -2,
    experience: 0.25,
    special: [],
  },
  elite: {
    armor_class: 2,
    attack_bonus: 2,
    hit_points: 2,
    damage_per_action: 1.2,
    saving_throws: 2,
    spell_dc: 2,
    initiative: 2,
    perception: 2,
    stealth: 2,
    experience: 2,
    special: ["paragon"],
  },
  solo: {
    armor_class: 2,
    attack_bonus: 2,
    hit_points: 4,
    damage_per_action: 1.2,
    saving_throws: 2,
    spell_dc: 2,
    initiative: 4,
    perception: 4,
    stealth: 4,
    experience: 4,
    special: ["paragon", "phase_66", "phase_33"],
  },
}

export const categories = [
  "aberration",
  "beast",
  "celestial",
  "construct",
  "dragon",
  "elemental",
  "fey",
  "fiend",
  "fiend (demon)",
  "fiend (devil)",
  "giant",
  "humanoid",
  "monstrosity",
  "ooze",
  "plant",
  "undead",
]

export const HitDies = {
  small: "d4",
  medium: "d6",
  large: "d8",
  huge: "d10",
  gargantuan: "d20",
}

export const sizes = keys(HitDies)

export const dies2hp = {
  d4: 2.5,
  d6: 3.5,
  d8: 4.5,
  d10: 5.5,
  d12: 6.5,
  d20: 10.5,
}

export const dies = keys(dies2hp)

export const alignments = [
  "lawful",
  "lawful good",
  "lawful evil",
  "neutral",
  "neutral good",
  "neutral evil",
  "chaotic",
  "chaotic good",
  "chaotic evil",
  "unaligned",
]

export const conditions = [
  "blinded",
  "charmed",
  "deafened",
  "exhaustion",
  "frightened",
  "grappled",
  "incapacitated",
  "invisible",
  "paralyzed",
  "petrified",
  "poisoned",
  "prone",
  "restrained",
  "stunned",
  "unconscious",
]

// https://www.5esrd.com/gamemastering/combat#Damage_Types
export const damage_types = [
  "bludgeoning",
  "cold",
  "fire",
  "force",
  "lightning",
  "necrotic",
  "piercing",
  "poison",
  "psychic",
  "radiant",
  "slashing",
  "thunder",
]

export const cr_exp = [
  { cr: "0", exp: 10 },
  { cr: "1/8", exp: 25 },
  { cr: "1/4", exp: 50 },
  { cr: "1/2", exp: 100 },
  { cr: "1", exp: 200 },
  { cr: "2", exp: 450 },
  { cr: "3", exp: 700 },
  { cr: "4", exp: 1100 },
  { cr: "5", exp: 1800 },
  { cr: "6", exp: 2300 },
  { cr: "7", exp: 2900 },
  { cr: "8", exp: 3900 },
  { cr: "9", exp: 5000 },
  { cr: "10", exp: 5900 },
  { cr: "11", exp: 7200 },
  { cr: "12", exp: 8400 },
  { cr: "13", exp: 10000 },
  { cr: "14", exp: 11500 },
  { cr: "15", exp: 13000 },
  { cr: "16", exp: 15000 },
  { cr: "17", exp: 18000 },
  { cr: "18", exp: 20000 },
  { cr: "19", exp: 22000 },
  { cr: "20", exp: 25000 },
  { cr: "21", exp: 33000 },
  { cr: "22", exp: 41000 },
  { cr: "23", exp: 50000 },
  { cr: "24", exp: 62000 },
  { cr: "25", exp: 75000 },
  { cr: "26", exp: 90000 },
  { cr: "27", exp: 105000 },
  { cr: "28", exp: 120000 },
  { cr: "29", exp: 135000 },
  { cr: "30", exp: 155000 },
]

// https://www.5esrd.com/languages/
export const languages = [
  "common",
  "dwarvish",
  "elvish",
  "giant",
  "gnomish",
  "goblin",
  "halfling",
  "orc",
  "abyssal",
  "celestial",
  "draconic",
  "deep speech",
  "infernal",
  "primordial",
  "sylvan",
  "undercommon",
]

// https://www.5esrd.com/gamemastering/monsters-foes/#Senses
export const special_senses = [
  "blindsight",
  "darkvision",
  "tremorsense",
  "truesight",
]
